### ISSUE TITLE
Apps Script API - unable to use API Explorer

### ISSUE THREAD

**Issue by Mattnificent** [gsuitedevs/go-samples#30] opened 2019-03-10 02:07 UTC
## Expected Behavior

The Apps Script API provides a scripts.run method that remotely executes a specified Apps Script function.

## Actual Behavior

The Apps Script API is either not working, or not properly documented enough for me to be able to use within a reasonable amount of time and effort.

## Steps to Reproduce the Problem

1.  Go to https://script.google.com/home/my
2. Click "+ New Script"
3. Enter project name: "TestScript"
4. Set the file "Code.gs" to the following:
`function setProp() {
  var props = PropertiesService.getScriptProperties().setProperty('testKey', 'testValue');
}
function clearProp() {
  PropertiesService.getScriptProperties().deleteAllProperties();
}
function testProp() {
  Logger.log('Props: ' + JSON.stringify(PropertiesService.getScriptProperties().getProperties(), null, 5));
}`
5. Quickly test the code by running setProp, then testProp, then press CTRL+ENTER to see the following:
`Props: {
     "testKey": "testValue"
}`
6. Clear the property by running clearProp, the testProp, and pressing CTRL+ENTER again. Should see:
`Props: {}`
7. Click Publish => Deploy as API Executable
8. Set the version name to "MyVersion" - leave it as accessible only to "myself"
9. Click "Close" on the new modal window that pops up
10. Click Resources => Cloud Platform Project
11. Click on the link immediately following the text "This script is currently associated with project:"
12. On the left side-panel, click "APIs and Services" => Library
13. In the search box, type "Script", and select "Apps Script API" from the results
14. Click Enable
15. Click "Try in API Explorer"
16. Click script.scripts.run
17. Put the script ID into the scriptId box (in URL of script editor page, or in File => Project Properties)
18. Click on the Request box, and from the "-- add a property --" selector, select "function"
19. Enter "setProp" as the function name
20. Click on "Authorize and Execute"
21. Agree to all the automatically selected scopes - click "Authorize and Execute"
22. Choose the same account that created the script project
23. The response is:

`403
cache-control:  private
content-encoding:  gzip
content-length:  128
content-type:  application/json; charset=UTF-8
date:  Sun, 10 Mar 2019 01:58:03 GMT
server:  ESF
vary:  Origin, X-Origin, Referer
{
 "error": {
  "code": 403,
  "message": "The caller does not have permission",
  "status": "PERMISSION_DENIED"
 }
}`

I have tried the following:
1. Adding more scopes to the code and authorizations
2. Setting devMode to true
3. Deploying from manifest file
4. Setting the API accessibility to "Anyone"
5. Running from .NET

In each case, I get the same 403 error.

## Specifications

None applicable

**Comment by sqrrrl** [comment] 2019-03-11 17:29
Changing the title. I'm pretty sure the issue is that the by default the API explorer is tied to a different developer project and doesn't have permission to call your script. You should still be able to call your script using your own clients, curl, etc.. so long as the access token you include in the request is tied to the same project as the script.

The API explorer has an option to use a custom client ID & secret. You can create an additional oauth client for your project and set the origin (IIRC should be https://developers.google.com) and call it that way.

**Comment by sqrrrl** [comment] 2019-03-11 17:30
Also, closing this issue since it's not an issue with any of the particular samples. For general help, suggest using StackOverflow.

**Closed by sqrrrl** 2019-03-11 17:30 UTC

**Comment by Mattnificent** [comment] 2019-03-11 22:29
Thank you, Steve.
I was not aware that I could change the Authentication in the API explorer.
![image](https://user-images.githubusercontent.com/4649715/54161920-27e2c900-442a-11e9-8492-61190d0ae10d.png)

**Comment by Mattnificent** [comment] 2019-04-09 13:07
You know what it doesn't say anywhere in the documentation?
All referenced projects must ALSO be a part of the same Google Cloud Project.
Why is all of this so poorly documented, full of ambiguous, or misleading error messages like "missing oath credential" when it IS there, but not correct for any mystery number of mystery reasons?
The whole system is filled with EXTREMELY unintuitive and misleading interfaces, like allowing me to put in an API key AND an oauth2 client ID, unintuitive as to how many deployment types a project can have, or what projects or documents properties as associated with, and so on, when it COULD BE EXPLAINED CLEARLY WITH A SIMPLE ENTITY DIAGRAM.
Was it rushed?
Are the developers stretched too thin?
Is English not the first language of the creators?
Is it just to keep the competition out?
Was it project managed by "business" majors, or women/minorities because "white men have been in power too long"?
Nothing will function AT ALL in this dynamically typed, systemically and morally loosely defined world Google is creating.
Keep it up, the future looks real bright, guys!

**Comment by erickoledadevrel** [comment] 2019-04-18 13:10
I apologize for the trouble you ran into. We do list this requirement in the documentation:

> Ensure that the script and the calling application share a common Cloud Platform (GCP) project. The GCP project must be a standard GCP project; default projects created for Apps Script projects are insufficient. The standard GCP project can be a new project or an existing one.

https://developers.google.com/apps-script/api/how-tos/execute

The interfaces in the library could certainly be more tailored, but at the moment we are using the generic client library infrastructure that all Google APIs use. This unfortunately makes it more possible to take wrong turns.

**Comment by Mattnificent** [comment] 2019-04-18 13:44
The text you quoted doesn't mention libraries - and neither does the error message.
Speaking of wrong turns, it seems like the API is completely insecure - if a user can call the run function, it appears that they can also call the get and update functions.
Who designed this? Lol...

**Comment by erickoledadevrel** [comment] 2019-04-18 14:17
That restrictions is true whether you use the Go library or any other. Reading and writing the script's contents require a different scope and that the user have ACLs on the script project.

We appreciate constructive criticism, but given that the discussion here no longer seems to be productive I'm going to lock this thread.
